name: ci
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  static:
    runs-on: ubuntu-latest
    name: "CI: Running ${{ matrix.test }} tests with perl v${{ matrix.perl-version }}"
    strategy:
      matrix:
        include:
          - test: static
            perl-version: 5.32
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}
    steps:
    - uses: actions/checkout@v2
    - name: getconf ARG_MAX
      run: |
        getconf ARG_MAX
